### PR TITLE
creating directories, adding meta tags and .gitignore file

### PR DESCRIPTION
**Pull request by shilomangam**
Hi @danyshaanan ,
I've created directories for stylesheets and js files, added some meta tags and created .gitignore file for the project.

Shilo

### CODE REVIEW

**Comment by danyshaanan** [comment]
This is great! However, these changes should be split into three commits:
* Extract css
* Add gitignore
* Edit HTML
It can still be grouped to one PR.

Technically, the way I'd do it is:
```bash
git reset @~
git status
git diff
git add -p . # This will let you interactively decide what's added, and commit different parts of the change
git commit # ...and again, 'git add...'
```

**Comment by danyshaanan** [comment]
Notice that a smaller PR introduced the css extraction - 78dacb43d1932e2b12e79723c0abc883edfbafed

**Comment by shilomangam** [comment]
Hi, I've created 3 commits due to your comments.

Thanks!

**Comment by danyshaanan** [comment]
Notice that 404aed70d94920d5cad8784d7615326fb451c7f4 and f9fb3802365e5802adfb624d202bc2143f569831 are not atomic, and do not represent separated valid changes. One will not work without the other. If they were in one PR without the gitignore commit, I could have squashed them, but through this PR, I can't, and since we'll have to edit this anyway, can you remove the directory creation and just have two commits: one to refactor the html, and another for the gitignore?

**Comment by shilomangam** [comment]
So, I've commited 2 changes. The first commit will be the index.html refactor without directories, the second commit will be the .gitignore creation.

**Comment by danyshaanan** [comment]
The commits' scopes now look good, but I've opened the html and the CSS was broken...

**Comment by shilomangam** [comment]
Fixed, please review.

**Comment by shilomangam** [comment]
Hi @danyshaanan ,
I've removed doctype tag and opened an [issue](https://github.com/danyshaanan/rotate/issues/17).

Please review my changes.
Thanks!

**Comment by danyshaanan** [comment]
Rebased locally and pushed to master as 87c4af12fb3be6327431f2d0906d53a939dd2ab9 and a397717a0c410e82d41a6d072556b56fc1a2310c.

**Pull request closed without merging**
